# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PostgreSQL With Init Scripts
      # You may pin to the exact commit or the version.
      # uses: m4nu56/postgresql-action@53809a8ffb454e0bb257840368384efd5c711a34
        uses: m4nu56/postgresql-action@1.0
        with:
          # Version of PostgreSQL to use
#           postgresql version: # optional, default is latest
          # POSTGRES_DB - name for the default database that is created
          postgresql db: test # optional, default is 
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: test # optional, default is 
          # POSTGRES_PASSWORD - superuser password
          postgresql password: test999 # optional, default is 
          # POSTGRES_INIT_SCRIPTS - directory containing DB init scripts
#           postgresql init scripts: # optional, default is 
